x-common: &commons
    deploy:
        resources:
            limits:
                cpus: '0.5'
                memory: 1G
    mem_swappiness: 0
    memswap_limit: 0
    healthcheck:
        interval: 10s
        timeout: 10s
        retries: 3
        start_period: 60s


services:
  app:
    image: collection-manager
    build: .
    ports:
      - 3000:3000
    healthcheck:
      test: ["CMD", "curl", "http://localhost:3000/"]